// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';


var months = /* array */[
  "January",
  "Febuary",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

var days = /* array */[
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday"
];

function suffix(num) {
  var match = +(num !== 11 && num % 10 === 1);
  if (match !== 0) {
    return num + "st";
  } else {
    var match$1 = +(num % 10 === 2 && num !== 12);
    if (match$1 !== 0) {
      return num + "nd";
    } else {
      var match$2 = +(num % 10 === 3 && num !== 13);
      if (match$2 !== 0) {
        return num + "rd";
      } else {
        return num + "th";
      }
    }
  }
}

function paddWithZeros(num) {
  var match = +(num < 10);
  if (match !== 0) {
    return "0" + num;
  } else {
    return num;
  }
}

function compiler(tokens, date, options) {
  var month = date.getMonth() | 0;
  var year = date.getFullYear() | 0;
  var hours = date.getHours() | 0;
  var seconds = date.getSeconds() | 0;
  var minutes = date.getMinutes() | 0;
  var day = date.getDate() | 0;
  var compiled = "";
  var index = 0;
  while(index < tokens.length) {
    var token = tokens[index];
    var match = token[/* t */0];
    switch (match) {
      case 0 : 
          compiled = compiled + token[/* v */1];
          break;
      case 1 : 
          compiled = compiled + months[month];
          break;
      case 2 : 
          var month$1 = months[month];
          compiled = compiled + month$1.slice(0, 3);
          break;
      case 3 : 
          compiled = compiled + year;
          break;
      case 4 : 
          compiled = compiled + (year + "").slice(2, 10);
          break;
      case 5 : 
          var day$1 = date.getDay() | 0;
          compiled = compiled + days[day$1];
          break;
      case 6 : 
          var match$1 = +(hours === 0 || hours === 12);
          var hour = match$1 !== 0 ? 12 : hours % 12;
          compiled = compiled + (
            options.padHours ? paddWithZeros(hour) : hour
          );
          break;
      case 7 : 
          compiled = compiled + paddWithZeros(minutes);
          break;
      case 8 : 
          compiled = compiled + paddWithZeros(seconds);
          break;
      case 9 : 
          var match$2 = +(hours >= 12);
          compiled = compiled + (
            match$2 !== 0 ? "PM" : "AM"
          );
          break;
      case 10 : 
          compiled = compiled + suffix(day);
          break;
      case 11 : 
          var match$3 = options.padDays;
          compiled = compiled + (
            match$3 !== 0 ? paddWithZeros(day) : day
          );
          break;
      case 12 : 
          var month$2 = month + 1 | 0;
          var match$4 = options.padMonth;
          compiled = compiled + (
            match$4 !== 0 ? paddWithZeros(month$2) : month$2
          );
          break;
      case 13 : 
          var match$5 = options.padHours;
          compiled = compiled + (
            match$5 !== 0 ? paddWithZeros(hours) : hours
          );
          break;
      
    }
    index = index + 1 | 0;
  };
  return compiled;
}

export {
  months        ,
  days          ,
  suffix        ,
  paddWithZeros ,
  compiler      ,
  
}
/* No side effect */
