// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';


var months = /* array */[
  "Januarys",
  "Febuary",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

var days = /* array */[
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday"
];

function suffix(num) {
  var match = +(num !== 11 && num % 10 === 1);
  if (match !== 0) {
    return num + "st";
  } else {
    var match$1 = +(num % 10 === 2 && num !== 12);
    if (match$1 !== 0) {
      return num + "nd";
    } else {
      var match$2 = +(num % 10 === 3 && num !== 13);
      if (match$2 !== 0) {
        return num + "rd";
      } else {
        return num + "th";
      }
    }
  }
}

function paddWithZeros(num) {
  var match = +(num < 10);
  if (match !== 0) {
    return "0" + num;
  } else {
    return num;
  }
}

function buildString(options, date, acc, token) {
  var month = date.getMonth() | 0;
  var year = date.getFullYear() | 0;
  var hours = date.getHours() | 0;
  var seconds = date.getSeconds() | 0;
  var minutes = date.getMinutes() | 0;
  var day = date.getDate() | 0;
  var match = token[/* t */0];
  switch (match) {
    case 0 : 
        return acc + token[/* v */1];
    case 1 : 
        return acc + months[month];
    case 2 : 
        var month$1 = months[month];
        return acc + month$1.slice(0, 3);
    case 3 : 
        return acc + year;
    case 4 : 
        return acc + (year + "").slice(2, 10);
    case 5 : 
        var day$1 = date.getDay() | 0;
        return acc + days[day$1];
    case 6 : 
        var match$1 = +(hours === 0 || hours === 12);
        var hour = match$1 !== 0 ? 12 : hours % 12;
        return acc + (
                options.padHours ? paddWithZeros(hour) : hour
              );
    case 7 : 
        return acc + paddWithZeros(minutes);
    case 8 : 
        return acc + paddWithZeros(seconds);
    case 9 : 
        var match$2 = +(hours >= 12);
        return acc + (
                match$2 !== 0 ? "PM" : "AM"
              );
    case 10 : 
        return acc + suffix(day);
    case 11 : 
        var match$3 = options.padDays;
        return acc + (
                match$3 !== 0 ? paddWithZeros(day) : day
              );
    case 12 : 
        var month$2 = month + 1 | 0;
        var match$4 = options.padMonth;
        return acc + (
                match$4 !== 0 ? paddWithZeros(month$2) : month$2
              );
    case 13 : 
        var match$5 = options.padHours;
        return acc + (
                match$5 !== 0 ? paddWithZeros(hours) : hours
              );
    
  }
}

function compiler(tokens, date, options) {
  return tokens.reduce(function (param, param$1) {
              return buildString(options, date, param, param$1);
            }, "");
}

export {
  months        ,
  days          ,
  suffix        ,
  paddWithZeros ,
  buildString   ,
  compiler      ,
  
}
/* No side effect */
