// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Parser   from "./parser.js";
import * as Compiler from "./compiler.js";

var defaultOptions = {
  padMonth: /* false */0,
  padDays: /* false */0,
  padHours: /* false */0
};

function parse(template, options) {
  var template$1 = Parser.parse(template);
  var optionsWithDefault = options === undefined ? defaultOptions : options;
  return {
          render: function (date) {
            return Compiler.compiler(template$1, date, optionsWithDefault);
          }
        };
}

function getTitle(user) {
  switch (user) {
    case 0 : 
        return "User: ";
    case 1 : 
        return "Moderator: ";
    case 2 : 
        return "Admin: ";
    
  }
}

var User = /* module */[/* getTitle */getTitle];

export {
  defaultOptions ,
  parse          ,
  User           ,
  
}
/* No side effect */
